Solution for Array Manipulation
Kvaibhav01/HackerRank-in-Java pull request #31
Opened 2019-10-04 19:27 UTC by Valdermaut

2019-10-05 07:54 UTC, Kvaibhav01 requested changes
1. Make sure to use braces like this:

```
static long arrayManipulation(int n, int[][] queries) {
    long[] computation = new long[n];
```

Instead of this:

```
static long arrayManipulation(int n, int[][] queries)
    {
    long[] computation = new long[n];
```

2. Change path from _Data Structures/Arrays/ArrayManipulation/Solution.java_ to _Data Structures/Arrays/**Array Manipulation**/Solution.java_.

2019-10-05 07:54 UTC, Kvaibhav01 commented on Data Structures/Arrays/ArrayManipulation/Solution.java
> +      computation[a] + = k;
This expression is illegal.

2019-10-06 18:21 UTC, Kvaibhav01 requested changes

2019-10-06 18:21 UTC, Kvaibhav01 commented on Data Structures/Arrays/Array Manipulation/Solution.java
> +  }
Please reformat the code. Don't use braces in the next line anywhere.

2019-10-06 19:35 UTC, Valdermaut commented on Data Structures/Arrays/ArrayManipulation/Solution.java
> +      computation[a] + = k;
okay I'll get onto it

2019-10-07 08:29 UTC, Kvaibhav01 commented on Data Structures/Arrays/Array Manipulation/Solution.java
> +    static long arrayManipulation(int n, int[][] queries){
Give space.

```suggestion
    static long arrayManipulation(int n, int[][] queries) {
```

2019-10-07 08:30 UTC, Kvaibhav01 requested changes
Check the suggested change and I'll merge the PR.

2019-10-07 10:56 UTC, Valdermaut commented
> Check the suggested change and I'll merge the PR.

yeah I have done it

2019-10-07 14:14 UTC, Kvaibhav01 approved these changes

2019-10-07 14:14 UTC, merged

2019-10-07 18:46 UTC, Valdermaut commented
great

On Mon, Oct 7, 2019 at 7:44 PM Vaibhav Khulbe <notifications@github.com>
wrote:

> Merged #31 <https://github.com/Kvaibhav01/HackerRank-Solutions/pull/31>
> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Kvaibhav01/HackerRank-Solutions/pull/31?email_source=notifications&email_token=AKMX4GTWE6ZQ3KMKOOKY7K3QNM74LA5CNFSM4I5TQCXKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOUB2J5EQ#event-2691997330>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKMX4GXA7O75QBKSHSUKW2LQNM74LANCNFSM4I5TQCXA>
> .
>