Added solution for preorder traversal in Java
Kvaibhav01/HackerRank-in-Java pull request #34
Opened 2019-10-09 00:22 UTC by SubhamPramanik

Added solution for 

https://www.hackerrank.com/challenges/tree-preorder-traversal/problem

in Java

2019-10-09 08:18 UTC, Kvaibhav01 commented on Data Structures/Trees/PostOrderTraversal_Solution.java
> +
Remove extra line spaces in lines 30 and 36.

2019-10-09 08:19 UTC, Kvaibhav01 requested changes
Rename path from _Data Structures/Trees/PostOrderTraversal_Solution.java_ to _Data Structures/Trees/**Tree: Postorder Traversal**/Solution.java_.

Also do the same in the second file.

2019-10-09 20:38 UTC, SubhamPramanik commented
Made the specified changes.

2019-10-10 08:41 UTC, Kvaibhav01 approved these changes
Good work!

2019-10-10 08:42 UTC, merged