Advanced Jim and the Skyscrapers problem solution
Kvaibhav01/HackerRank-in-Java pull request #35
Opened 2019-10-10 11:19 UTC by michaelmdev

2019-10-10 14:48 UTC, Kvaibhav01 commented on Data Structures/Advanced/Jim and the Skyscrapers/Solution.java
> +            // 2) прибить меньших
Please add the English conversion to the comments.

2019-10-10 14:48 UTC, Kvaibhav01 requested changes
Check the comment.

2019-10-10 19:32 UTC, michaelmdev commented on Data Structures/Advanced/Jim and the Skyscrapers/Solution.java
> +            // 2) прибить меньших
fixed

2019-10-11 10:44 UTC, Kvaibhav01 approved these changes
Good work!

2019-10-11 10:45 UTC, merged